# action.yml
name: 'easy configurable phpstan'
author: zalexki
description: 'An easy way to run a configurable php-stan on your project without adding it as a dependency.'
branding:
  icon: 'check'  
  color: 'blue'
inputs:
  other-cmds:
    description: 'Add some configs'
    required: false
    default: 'analyse classes -c /base.neon'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.other-cmds }}